project_id = "zxhwjoysctshyqukznvq"

[functions.send-push-notification]
verify_jwt = true

[functions.send-bulk-sms]
verify_jwt = true

[functions.send-bulk-email]
verify_jwt = true

[functions.generate-manifest]
verify_jwt = false